### ISSUE TITLE
`getNeighborSitesForSite` bug - How to get a graph only spanning between voronoi neighbor sites?

### ISSUE THREAD

**Issue by Domiii** [nodename/as3delaunay#8]
When looking at the Delaunay graph, Voronoi sites on the region boundary are connected to other sites that are not immediate Voronoi neighbors, but also happen to touch on the same boundary line (probably to ensure convexity of the triangulation).

When playing around with [the demo](http://nodename.com/blog/2009/05/11/a-voronoi-toy/), you can easily see the problem. I highlighted one such edge on the right-hand side with a long white box.The edge connects two Voronoi sites are not immediate neighbors:

![image](https://cloud.githubusercontent.com/assets/282899/8521520/033b5810-2417-11e5-8fac-11b22e2edd56.png)

If this is intended, then the [`getNeighborSitesForSite` method](https://github.com/nodename/as3delaunay/blob/master/src/com/nodename/Delaunay/Voronoi.as#L118) should be renamed to `getDelaunayNeighborSitesForSite` or so, to make sure that this is not a neighbor in the sense of the Voronoi diagram?

Also, do you have a quick fix for getting such a Voronoi graph that only connects Voronoi neighbor sites?

**Comment by nodename** [comment]
This result is indeed intended, because the Delaunay triangulation by definition includes the convex hull. A graph that omits the hull edges would not be the Delaunay triangulation.
